export './about/about_screen.dart';
export './episode_details/episode_details_screen.dart';
export './episode_details_captain_fact/episode_details_captain_fact_screen.dart';
export './home/home_screen.dart';
export './search/search_screen.dart';
export './video_player/video_player_screen.dart';
export 'categories/categories_screen.dart';
export 'categories/category_videos_screen.dart';
export 'comics/comics_screen.dart';
